LPS-190017
kevhlee/liferay-portal pull request #110
Opened 2023-07-11 17:18 UTC by TamyrisTorres

LPS-190017

2023-07-11 17:18 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-07-11 17:28 UTC, TamyrisTorres commented
ci:test:sf

2023-07-11 17:28 UTC, TamyrisTorres commented
ci:test:relevant

2023-07-11 17:30 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-19.liferay.com/job/test-portal-source-format/6986/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-19.liferay.com/userContent/jobs/test-portal-source-format/builds/6986/jenkins-report.html">here</a>.</b></p>

2023-07-11 17:53 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 25 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c641fd699669191c21f5c20429da55fc6a1e5490">c641fd699669191c21f5c20429da55fc6a1e5490</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/TamyrisTorres/liferay-portal/tree/LPS-190017">LPS-190017</a><br/>Branch GIT ID: <a href="https://github.com/TamyrisTorres/liferay-portal/commit/bbd3661a33aab4529f838e02c615bfbdf7853e13">bbd3661a33aab4529f838e02c615bfbdf7853e13</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-19.liferay.com/job/test-portal-source-format/6986/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-19.liferay.com/userContent/jobs/test-portal-source-format/builds/6986/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 3 formatting issues:
     [java] 1: Use extension 'markdown' instead of 'md': ./modules/test/poshi/poshi-vscode/README.md (SourceCheck:MarkdownFileExtensionCheck)
     [java] 2: ./modules/apps/object/object-test/src/testFunctional/macros/json/JSONObject.macro expected:&lt;...atch(\$\{curl\});
     [java]   \}
     [java] 
     [java]   []macro updateObjectFi...&gt; but was:&lt;...atch(\$\{curl\});
     [java]   \}
     [java] 
     [java]   [@summary = "This calls the patchObjectField Headless API endpoint to update a configuration within an object field"
     [java]   ]macro updateObjectFi...&gt;
     [java] 3: ./modules/apps/document-library/document-library-service/src/main/java/com/liferay/document/library/internal/bulk/selection/action/EditCategoriesBulkSelectionAction.java expected:&lt;...et&lt;Long&gt; _toLongSet([Map&lt;String, Serializable&gt; map, String key) \{]
     [java]     try \{
     [java]       return S...&gt; but was:&lt;...et&lt;Long&gt; _toLongSet([
     [java]     Map&lt;String, Serializable&gt; map, String key) \{
     [java] ]
     [java]     try \{
     [java]       return S...&gt;
     [java] 
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:466)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:299)
[stopwatch] [run.batch.test.action: 22:20.055 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:456: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:610: Java returned: 1
      [get] Getting: http://test-1-19/job/test-portal-source-format/6986//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20230711105317640.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20230711105317640.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null315696064.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[beanshell] Truncating errors in /opt/dev/projects/github/liferay-portal/portal-impl/test-results/TEST-JenkinsLogAssertTest.xml
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null2014419460
[junitreport] Loading stylesheet jar:file:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 274ms</pre></details></html>

2023-07-11 17:57 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-19.liferay.com/job/test-portal-source-format/6986/">test-portal-source-format#6986</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-19.liferay.com/userContent/jobs/test-portal-source-format/builds/6986/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/kevhlee/liferay-portal/pull/110">kevhlee#110</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2378152815">[master] ci:test:sf - TamyrisTorres &gt; kevhlee - PR#110 - 2023-07-11[10:28:58]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-19.liferay.com/job/publish-testray-report/3673/">publish-testray-report#3673</a><br/></div></div>

2023-07-11 18:27 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/1863/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1863/jenkins-report.html">here</a>.</b></p>

2023-07-11 20:16 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 29 out of 29 jobs passed</h3><h3>:x: ci:test:relevant - 54 out of 56 jobs passed in 1 hour 49 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c641fd699669191c21f5c20429da55fc6a1e5490">c641fd699669191c21f5c20429da55fc6a1e5490</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c641fd699669191c21f5c20429da55fc6a1e5490">c641fd699669191c21f5c20429da55fc6a1e5490</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2378195148">EE Development Acceptance (master) - 4681 - 2023-07-11[08:39:01]</a></p><details><summary><strong>ci:test:stable - 29 out of 29 jobs PASSED</strong></summary><details><summary><strong>29 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 54 out of 56 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/1863/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>build-iw-jdk8<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/700595/">build-iw-jdk8/0/0</a></li></ul></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/234104/">central-requirements-jdk8/0/0</a></li></ul></li><li>empty-osgi-core-dir-mysql57-jdk8<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/727868/">empty-osgi-core-dir-mysql57-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-db2115-jdk8<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/631193/">functional-smoke-tomcat90-db2115-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-hypersonic20-jdk8<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/659191/">functional-smoke-tomcat90-hypersonic20-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk11_open<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/727867/"><strike>functional-smoke-tomcat90-mysql57-jdk11_open/0/0</strike></a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/200192/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-smoke-tomcat90-oracle193-jdk8<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/700600/">functional-smoke-tomcat90-oracle193-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-postgresql144-jdk8<ul><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/229617/">functional-smoke-tomcat90-postgresql144-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-sqlserver2019-jdk8<ul><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/232564/">functional-smoke-tomcat90-sqlserver2019-jdk8/0/0</a></li></ul></li><li>functional-smoke-wildfly180-mariadb104-jdk8<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/611132/">functional-smoke-wildfly180-mariadb104-jdk8/0/0</a></li></ul></li><li>functional-smoke-wildfly180-mariadb106-jdk8<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/611131/">functional-smoke-wildfly180-mariadb106-jdk8/0/0</a></li></ul></li><li>functional-tomcat90-mysql57-chrome100-jdk8<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/727869/">functional-tomcat90-mysql57-chrome100-jdk8/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/233392/">functional-upgrade-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/476839/">functional-upgrade-tomcat90-mysql57-jdk8/0/1</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/227049/">functional-upgrade-tomcat90-mysql57-jdk8/0/2</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/229619/">functional-upgrade-tomcat90-mysql57-jdk8/0/3</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/559908/">functional-upgrade-tomcat90-mysql57-jdk8/0/4</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/565545/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/631192/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/1</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/231855/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/2</a></li></ul></li><li>functional-upgrade-tomcat90-postgresql144-jdk8<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/611134/">functional-upgrade-tomcat90-postgresql144-jdk8/0/0</a></li></ul></li><li>js-unit-jdk8<ul><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/218060/">js-unit-jdk8/0/0</a></li></ul></li><li>lpkg-controller-mysql57-jdk8<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/631299/">lpkg-controller-mysql57-jdk8/0/0</a></li></ul></li><li>modules-compile-jdk8<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/700596/">modules-compile-jdk8/0/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/631190/">modules-compile-jdk8/0/1</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/202100/">modules-compile-jdk8/0/2</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/700597/">modules-compile-jdk8/0/3</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/611133/">modules-compile-jdk8/0/4</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/232565/">modules-compile-jdk8/0/5</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/559907/">modules-compile-jdk8/0/6</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/635799/">modules-compile-jdk8/0/7</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/190209/">modules-compile-jdk8/0/8</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/659190/">modules-compile-jdk8/0/9</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/727865/">modules-compile-jdk8/0/10</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/727866/">modules-compile-jdk8/0/11</a></li></ul></li><li>modules-integration-mysql57-jdk8<ul><li><a h [...]

2023-07-11 20:21 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/1863/">test-portal-acceptance-pullrequest(master)#1863</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1863/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/kevhlee/liferay-portal/pull/110">kevhlee#110</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2378336188">[master] ci:test:relevant - TamyrisTorres &gt; kevhlee - PR#110 - 2023-07-11[11:27:24]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/3735/">publish-testray-report#3735</a><br/></div></div>

2023-07-14 18:54 UTC, kevhlee commented
Taking a look.

2023-07-14 19:50 UTC, kevhlee requested changes
Hi @TamyrisTorres, I am a little confused about what pattern is being automated here and what problem it is solving here. The ticket talks about `DestinationConfiguration`, yet the configuration class is not involved in any way in this check.

Also, just checking `RejectedExecutionHandler` variable declarations would not prevent `CallerRunsPolicy` being used as a `RejectedExecutionHandler`. For example, in our own code, we have usages like this:

```java
ThreadPoolExecutor threadPoolExecutor = new ThreadPoolExecutor(
	1, 2, TestUtil.KEEPALIVE_TIME, TimeUnit.MILLISECONDS, true, 3,
	new CallerRunsPolicy(), Executors.defaultThreadFactory(),
	markerThreadPoolHandler);
```

Can you elaborate on what problem this check solves?

2023-07-14 19:50 UTC, kevhlee commented on modules/util/source-formatter/src/main/java/com/liferay/source/formatter/check/UpgradeJavaThreadPoolExecutorClassCheck.java
> +		"\\w+\\s*\\w+\\s*[^)]\\s*(\\s*new\\s*CallerRunsPolicy\\s*\\(\\))");
We could change this regex to match `RejectedExecutionHandler` variable declarations. That way, you do not have to extract the method call and check the class name.

2023-07-14 19:50 UTC, kevhlee commented on modules/util/source-formatter/src/main/java/com/liferay/source/formatter/check/UpgradeJavaThreadPoolExecutorClassCheck.java
> +		"\\w+\\s*\\w+\\s*[^)]\\s*(\\s*new\\s*CallerRunsPolicy\\s*\\(\\))");
Also shouldn't the first `\\s*` be `\\s+` instead? `\\s+` ensures that at least 1 whitespace character is matched.

2023-07-17 16:48 UTC, nicolas-sss commented
> Hi @TamyrisTorres, I am a little confused about what pattern is being automated here and what problem it is solving here. The ticket talks about `DestinationConfiguration`, yet the configuration class is not involved in any way in this check.
> 
> Also, just checking `RejectedExecutionHandler` variable declarations would not prevent `CallerRunsPolicy` being used as a `RejectedExecutionHandler`. For example, in our own code, we have usages like this:
> 
> ```java
> ThreadPoolExecutor threadPoolExecutor = new ThreadPoolExecutor(
> 	1, 2, TestUtil.KEEPALIVE_TIME, TimeUnit.MILLISECONDS, true, 3,
> 	new CallerRunsPolicy(), Executors.defaultThreadFactory(),
> 	markerThreadPoolHandler);
> ```
> 
> It is not clear from the test inputs what problem this check is trying to solve. Can you elaborate on the exact problem?

Hi @kevhlee, the pattern for this check isn't properly about the DestinationConfiguration, sorry about that. It's about this pattern:

Before: 

```java
import com.liferay.portal.kernel.concurrent.CallerRunsPolicy;
import com.liferay.portal.kernel.concurrent.RejectedExecutionHandler;
import com.liferay.portal.kernel.concurrent.ThreadPoolExecutor;

RejectedExecutionHandler rejectedExecutionHandler =
				new CallerRunsPolicy();
```

Expected:
```java
import java.util.concurrent.RejectedExecutionHandler;
import java.util.concurrent.ThreadPoolExecutor;

RejectedExecutionHandler rejectedExecutionHandler =
				new ThreadPoolExecutor.CallerRunsPolicy();
```

The imports changed and the declaration should not use `new CallerRunsPolicy()` anymore.

2023-07-17 21:57 UTC, kevhlee commented
Thanks for the explanation, @nicolas-sss. However, that only cleared things up for me only a little bit. To me, this check does not do much because it only tackles variable declarations, as I mentioned in my other comments. Why just variable declarations? Why not ___any usages___ of `com.liferay.portal.kernel.concurrent.CallerRunsPolicy`?

2023-07-18 17:06 UTC, nicolas-sss commented
> Thanks for the explanation, @nicolas-sss. However, that only cleared things up for me only a little bit. To me, this check does not do much because it only tackles variable declarations. Why just variable declarations? Why not _**any usage**_ of `com.liferay.portal.kernel.concurrent.CallerRunsPolicy`? It does not handle the input case that I showed in my other comment. It is still unclear how this check is useful.
> 
> Also, this check only works if `ThreadPoolExecutor` is also imported. But what if `com.liferay.portal.kernel.concurrent.CallerRunsPolicy` is used without a `ThreadPoolExecutor`? What do we do then?

Hi @kevhlee,  the pattern is about the change on `RejectedExecutionHandler` use. Because of this, it is only in the variable declaration, the Liferay class `com.liferay.portal.kernel.concurrent.CallerRunsPolicy` still exists and is used the same in its previous input, in its previous input it does not need to be changed, only when related directly to the `RejectedExecutionHandler`. 
Previously Liferay classes used the 
`com.liferay.portal.kernel.concurrent.RejectedExecutionHandler` class as a variable that used the `com.liferay.portal.kernel.concurrent.CallerRunsPolicy`. But now is to switch to java.util.concurrent.RejectedExecutionHandler which uses the callers returned always by `java.util.concurrent.ThreadPoolExecutor`.

So after replacing import com.liferay.portal.kernel.concurrent.RejectedExecutionHandler by java.util.concurrent.RejectedExecutionHandler. We change the declaration from this:

```java
RejectedExecutionHandler rejectedExecutionHandler =
				new CallerRunsPolicy();
```

to this:

```java
RejectedExecutionHandler rejectedExecutionHandler =
			new ThreadPoolExecutor.CallerRunsPolicy() {...}
```

2023-07-18 23:13 UTC, kevhlee requested changes

2023-07-18 23:13 UTC, kevhlee commented on modules/util/source-formatter/src/main/java/com/liferay/source/formatter/check/UpgradeJavaThreadPoolExecutorClassCheck.java
> +					"RejectExecutionHandler") &&
Should be `RejectedExecutionHandler`.

2023-07-18 23:20 UTC, kevhlee requested changes

2023-07-18 23:20 UTC, kevhlee commented on modules/util/source-formatter/src/main/java/com/liferay/source/formatter/check/UpgradeJavaThreadPoolExecutorClassCheck.java
> +					"RejectExecutionHandler") &&
This should be `RejectedExecutionHandler`.

2023-07-18 23:20 UTC, kevhlee commented on modules/util/source-formatter/src/main/java/com/liferay/source/formatter/check/UpgradeJavaThreadPoolExecutorClassCheck.java
> +				newContent, "java.util.concurrent.ThreadPoolExecutor");
Hey @nicolas-sss, we discussed this earlier. As you suggested, we need to also change the import `com.liferay.portal.kernel.concurrent.RejectedExecutionHandler` to `java.util.concurrent.RejectedExecutionHandler`.

2023-07-19 19:11 UTC, nicolas-sss commented
Resent at https://github.com/kevhlee/liferay-portal/pull/123

2023-07-19 19:12 UTC, nicolas-sss commented
@kevhlee please close this Pr and review the new one

2023-07-21 18:20 UTC, closed without merging