LPS-185518
kevhlee/liferay-portal pull request #77
Opened 2023-06-08 17:11 UTC by TamyrisTorres

LPS-185518

2023-06-08 17:11 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-06-08 17:14 UTC, TamyrisTorres commented
ci:test:sf

2023-06-08 17:16 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-38.liferay.com/job/test-portal-source-format/4624/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/4624/jenkins-report.html">here</a>.</b></p>

2023-06-08 18:04 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 21 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/bcd9d8de265c6d9f5483d6ea5bb6dda1c2188ca8">bcd9d8de265c6d9f5483d6ea5bb6dda1c2188ca8</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/TamyrisTorres/liferay-portal/tree/LPS-185518">LPS-185518</a><br/>Branch GIT ID: <a href="https://github.com/TamyrisTorres/liferay-portal/commit/abf4542809481bd9d61baa62c577d9fdd4b3379c">abf4542809481bd9d61baa62c577d9fdd4b3379c</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-38.liferay.com/job/test-portal-source-format/4624/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/4624/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 3 formatting issues:
     [java] 1: ./modules/apps/portal-remote/portal-remote-jaxrs-whiteboard/build.gradle expected:&lt;...jax.rs.whiteboard", []version: "2.0.0"
     [java]   co...&gt; but was:&lt;...jax.rs.whiteboard", [transitive: false, ]version: "2.0.0"
     [java]   co...&gt;
     [java] 2: ./modules/third-party/org-apache-aries-component-dsl/build.gradle expected:&lt;...dsl.component-dsl", [transitive: false, version: "1.2.2"]
     [java]   compileOnly group:...&gt; but was:&lt;...dsl.component-dsl", [version: "1.2.2", transitive: false]
     [java]   compileOnly group:...&gt;
     [java] 3: ./modules/apps/object/object-rest-test/src/testIntegration/java/com/liferay/object/rest/internal/resource/v1_0/test/util/UserAccountTestUtil.java expected:&lt;...serAccountJSONObject[(
     [java]       SystemObjectDefinitionManager systemObjectDefinitionManager,
     [java]       JSONObject userAccountJSONObject, Map&lt;String, Serializable&gt; values)
     [java]     throws Exception \{
     [java] 
     [java]     UserAccount userAccount = randomUserAccount();
     [java] 
     [java]     JaxRsApplicationDescriptor jaxRsApplicationDescriptor =
     [java]       systemObjectDefinitionManager.getJaxRsApplicationDescriptor();
     [java] 
     [java]     return HTTPTestUtil.invoke(
     [java]       _toBody(userAccount, values),
     [java]       StringBundler.concat(
     [java]         jaxRsApplicationDescriptor.getRESTContextPath(),
     [java]         StringPool.SLASH, userAccountJSONObject.get("id")),
     [java]       Http.Method.PUT);
     [java]   \}
     [java] 
     [java]   public static JSONObject updateUserAccountJSONObjectByExternalReferenceCode(
     [java]       SystemObjectDefinitionManager systemObjectDefinitionManager,
     [java]       JSONObject userAccountJSONObject, Map&lt;String, Serializable&gt; values)
     [java]     throws Exception \{
     [java] 
     [java]     UserAccount userAccount = randomUserAccount();
     [java] 
     [java]     JaxRsApplicationDescriptor jaxRsApplicationDescriptor =
     [java]       systemObjectDefinitionManager.getJaxRsApplicationDescriptor();
     [java] 
     [java]     return HTTPTestUtil.invoke(
     [java]       _toBody(userAccount, values),
     [java]       StringBundler.concat(
     [java]         jaxRsApplicationDescriptor.getRESTContextPath(),
     [java]         "/by-external-reference-code/",
     [java]         userAccountJSONObject.get("externalReferenceCode]")),
     [java]       Http.Method....&gt; but was:&lt;...serAccountJSONObject[ByExternalReferenceCode(</pre></details></html>

2023-06-08 18:08 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-38.liferay.com/job/test-portal-source-format/4624/">test-portal-source-format#4624</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/4624/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/kevhlee/liferay-portal/pull/77">kevhlee#77</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2344804773">[master] ci:test:sf - TamyrisTorres &gt; kevhlee - PR#77 - 2023-06-08[10:14:42]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-38.liferay.com/job/publish-testray-report/16633/">publish-testray-report#16633</a><br/></div></div>

2023-06-09 17:22 UTC, TamyrisTorres commented
ci:test:sf

2023-06-09 17:22 UTC, TamyrisTorres commented
ci:test:relevant

2023-06-09 17:53 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 31 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/a5dc906f7ab190d5ce0893b31f306fa00a2d7d35">a5dc906f7ab190d5ce0893b31f306fa00a2d7d35</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/TamyrisTorres/liferay-portal/tree/LPS-185518">LPS-185518</a><br/>Branch GIT ID: <a href="https://github.com/TamyrisTorres/liferay-portal/commit/abf4542809481bd9d61baa62c577d9fdd4b3379c">abf4542809481bd9d61baa62c577d9fdd4b3379c</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-6.liferay.com/job/test-portal-source-format/6525/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-6.liferay.com/userContent/jobs/test-portal-source-format/builds/6525/jenkins-report.html">here</a>.</h5></details></html>

2023-06-09 18:01 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-6.liferay.com/job/test-portal-source-format/6525/">test-portal-source-format#6525</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-6.liferay.com/userContent/jobs/test-portal-source-format/builds/6525/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/kevhlee/liferay-portal/pull/77">kevhlee#77</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2345791375">[master] ci:test:sf - TamyrisTorres &gt; kevhlee - PR#77 - 2023-06-09[10:23:14]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-6.liferay.com/job/publish-testray-report/4075/">publish-testray-report#4075</a><br/></div></div>

2023-06-09 19:54 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest(master)/8353/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8353/jenkins-report.html">here</a>.</b></p>

2023-06-09 22:09 UTC, kevhlee commented
Taking a look.

2023-06-09 22:40 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:relevant - 0 out of 1 jobs passed in 2 hours 46 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/a5dc906f7ab190d5ce0893b31f306fa00a2d7d35">a5dc906f7ab190d5ce0893b31f306fa00a2d7d35</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/a5dc906f7ab190d5ce0893b31f306fa00a2d7d35">a5dc906f7ab190d5ce0893b31f306fa00a2d7d35</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2345761822">EE Development Acceptance (master) - 4600 - 2023-06-09[06:49:36]</a></p><details><summary><strong>ci:test:relevant - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest(master)/8353/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8353/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest(master)/8353/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><pre>HOSTNAME=test-1-31-72.lax.liferay.com
JAVA_HOME=/opt/java/jdk8
MASTER_HOSTNAME=test-1-31
ORACLE_HOME=/u01/app/oracle/product/12.2.0/db_1
ORACLE_SID=oracl
PATH=/opt/java/ant/bin:/opt/java/jdk8/bin:/opt/java/maven/bin:/usr/lib64/qt-3.3/bin:/opt/sybase/OCS-16_0/bin/:/u01/app/oracle/product/12.2.0/db_1/bin:/opt/ibm/db2/V11.1/bin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/sbin:/bin
SYBASE_ASE=ASE-16_0
Execute: ant -f commands/build-common.xml run-ant-target -Dant.file.name=build-test-portal-acceptance-pullrequest.xml -Dant.target= -lib commands/../lib/jenkins -propertyfile /opt/dev/projects/github/liferay-jenkins-ee/start.properties
Build step 'Execute shell' marked build as failure
[PostBuildScript] - [INFO] Executing post build scripts.
[liferay-jenkins-ee] \$ /bin/bash -e -x /tmp/jenkins9952090852250753896.sh
+ echo 'Execute: build-test-portal-acceptance-pullrequest.sh stop-current-job'
Execute: build-test-portal-acceptance-pullrequest.sh stop-current-job
+ commands/build-test-portal-acceptance-pullrequest.sh stop-current-job
ANT_OPTS=-Dhttp.nonProxyHosts="cloud*|files.liferay.org.es|it.liferay.com|localhost|mirrors-no-cache.lax.liferay.com|release*|test*" -server -verbose:gc -Xloggc:/tmp/ant-gc.log -Xms1024m -Xmx4096m -Xss2m -Xverify:none -XX:+DisableExplicitGC -XX:+HeapDumpOnOutOfMemoryError -XX:+PrintGCCause -XX:+PrintGCDetails -XX:+UseParallelOldGC -XX:HeapDumpPath=/tmp/ant-oom-heap-dump.bin -XX:MaxNewSize=512m -XX:MaxMetaspaceSize=512m -XX:MaxTenuringThreshold=0 -XX:NewSize=256m -XX:MetaspaceSize=100m -XX:SurvivorRatio=65536 -XX:TargetSurvivorRatio=0
HOSTNAME=test-1-31-72.lax.liferay.com
JAVA_HOME=/opt/java/jdk8
MASTER_HOSTNAME=test-1-31
ORACLE_HOME=/u01/app/oracle/product/12.2.0/db_1
ORACLE_SID=oracl
PATH=/opt/java/ant/bin:/opt/java/jdk8/bin:/opt/java/maven/bin:/usr/lib64/qt-3.3/bin:/opt/sybase/OCS-16_0/bin/:/u01/app/oracle/product/12.2.0/db_1/bin:/opt/ibm/db2/V11.1/bin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/sbin:/bin
SYBASE_ASE=ASE-16_0
Execute: ant -f commands/build-common.xml run-ant-target -Dant.file.name=build-test-portal-acceptance-pullrequest.xml -Dant.target=stop-current-job -lib commands/../lib/jenkins -propertyfile /opt/dev/projects/github/liferay-jenkins-ee/start.properties</pre></div></li></ol><h4>For upstream results, click <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2023-06-09 22:42 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest(master)/8353/">test-portal-acceptance-pullrequest(master)#8353</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8353/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/kevhlee/liferay-portal/pull/77">kevhlee#77</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2346137941">[master] ci:test:relevant - TamyrisTorres &gt; kevhlee - PR#77 - 2023-06-09[12:53:46]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-31.liferay.com/job/publish-testray-report/19983/">publish-testray-report#19983</a><br/></div></div>

2023-06-09 23:34 UTC, kevhlee requested changes

2023-06-09 23:34 UTC, kevhlee commented on modules/util/source-formatter/src/main/java/com/liferay/source/formatter/check/UpgradeJavaSetResultsSetTotalMethodCheck.java
> +			if (_hasClassName("SearchContainer", content, methodCall)) {
Is specifying the class name necessary? Unless we are dealing with multiple classes, the class name will always be `SearchContainer`.

2023-06-09 23:34 UTC, kevhlee commented on modules/util/source-formatter/src/test/resources/com/liferay/source/formatter/dependencies/expected/upgrade/UpgradeJavaSetResultsSetTotalMethodCheck.testjava
> +
We should remove the newline here.

You can do this by obtaining the method call's indentation using `JavaSourceUtil.getIndent()` and do something like this:

```java
String indent = JavaSourceUtil.getIndent(...);

String fullMethodCall = StringBundler.concat(
    StringPool.NEW_LINE, indent, methodCall, StringPool.SEMICOLON, StringPool.NEW_LINE);

newContent = StringUtil.replace(newContent, fullMethodCall, "");
```

2023-06-12 21:33 UTC, closed without merging